### ISSUE TITLE
Issues compiling zonation

### ISSUE THREAD

**Issue by cmzambranat** [cbig/zonation-core#19]
Hi,

Hope you guys can provide some help. I followed the compilation instructions but I'm having some problems when compiling `zonation`. I'm on Debian GNU/Linux 9.5 (stretch). 

Here are the errors that I'm getting:

```  7%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/core.cpp.o
[  8%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o
[ 10%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_load.cpp.o
[ 11%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_save.cpp.o
/home/users/repos/zonation/zonation-core-master/zig4lib/core.cpp: In constructor ‘ZInterprocess::Core::Core(const FilePath&, QString&)’:
/home/user/repos/zonation/zonation-core-master/zig4lib/core.cpp:159:2: error: ‘cout’ is not a member of ‘std’
  std::cout << resultMsg.toStdString() << std::endl;
  ^~~
[ 13%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o
zig4lib/CMakeFiles/zig4lib.dir/build.make:82: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/core.cpp.o' failed
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/core.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/user/repos/zonation/zonation-core-master/zig4lib/io.cpp: In function ‘void print_help(QString)’:
/home/user/repos/zonation/zonation-core-master/zig4lib/io.cpp:57:3: error: ‘cout’ is not a member of ‘std’
   std::cout << "zig4 (" << command.toStdString() << ")\n"
   ^~~
/home/user/repos/zonation/zonation-core-master/zig4lib/io.cpp: In function ‘void print_version()’:
/home/user/repos/zonation/zonation-core-master/zig4lib/io.cpp:94:3: error: ‘cout’ is not a member of ‘std’
   std::cout <<
   ^~~
zig4lib/CMakeFiles/zig4lib.dir/build.make:154: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o' failed
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o] Error 1
/home/user/repos/zonation/zonation-core-master/zig4lib/io_admu_load.cpp:21:51: fatal error: boost/spirit/home/phoenix/container.hpp: No such file or directory
 #include <boost/spirit/home/phoenix/container.hpp>
                                                   ^
compilation terminated.
zig4lib/CMakeFiles/zig4lib.dir/build.make:178: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o' failed
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/io_admu_load.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/all' failed
make[1]: *** [zig4lib/CMakeFiles/zig4lib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2```


Thanks!

**Comment by jlehtoma** [comment]
@cmzambranat looks like you (at least) two issues here.

```
[  8%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o
[ 10%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_load.cpp.o
[ 11%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/ini_save.cpp.o
/home/users/repos/zonation/zonation-core-master/zig4lib/core.cpp: In constructor ‘ZInterprocess::Core::Core(const FilePath&, QString&)’:
/home/user/repos/zonation/zonation-core-master/zig4lib/core.cpp:159:2: error: ‘cout’ is not a member of ‘std’
  std::cout << resultMsg.toStdString() << std::endl;
```
 
Can probably be [fixed](https://stackoverflow.com/questions/11375949/cout-is-not-a-member-of-std) by adding `#include <iostream>` at the beginning of `core.cpp`. However, this indicates that there are comparability issues with the code and your compiler/libraries. Most likely, the latter are too new for the code.

The other problem

```
zig4lib/CMakeFiles/zig4lib.dir/build.make:154: recipe for target 'zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o' failed
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o] Error 1
/home/user/repos/zonation/zonation-core-master/zig4lib/io_admu_load.cpp:21:51: fatal error: boost/spirit/home/phoenix/container.hpp: No such file or directory
 #include <boost/spirit/home/phoenix/container.hpp>
```

is definitely related to a too recent version of boost in your system (see e.g. #15). 

The safest bet is to revert to an old but proven distro and version, e.g. Ubuntu 14.04. Updating Zonation code would be great too, but currently nobody is working on this.

**Comment by cmzambranat** [comment]
Thank you! 
I tried to compile in Ubuntu 14.04 (newest boost) and it failed again. I think the problem now is with the  latest version of the proj4 library (currently 5.2.0). I'll keep trying and report back. 

```
[  1%] Generating moc_observer.cxx
[  3%] Generating moc_core.cxx
[  4%] Generating moc_io_arg.cxx
[  6%] Generating moc_manager.cxx
Scanning dependencies of target zig4lib
[  7%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io.cpp.o
[  9%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/spirit_util.cpp.o
[ 10%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io_groups_save.cpp.o
[ 12%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/io_ig_load.cpp.o
[ 13%] Building CXX object zig4lib/CMakeFiles/zig4lib.dir/proj.cpp.o
In file included from /home/user/zonation/zonation-core-master/zig4lib/proj.h:5:0,
                 from /home/user/zonation/zonation-core-master/zig4lib/proj.cpp:1:
/home/user/zonation/zonation-core-master/zig4lib/manager.h: In instantiation of ‘FileRef<Format>::operator bool() const [with Format = ZUnknownFormat]’:
/home/user/zonation/zonation-core-master/zig4lib/proj_io_util.h:25:9:   required from ‘bool LoadOptionalFile::operator()(FileRef<Format>&, const FilePath&) [with Format = ZUnknownFormat]’
/home/user/zonation/zonation-core-master/zig4lib/proj.cpp:61:57:   required from here
/home/user/zonation/zonation-core-master/zig4lib/manager.h:173:11: error: cannot convert ‘const boost::intrusive_ptr<FileImpl<ZUnknownFormat> >’ to ‘bool’ in return
    return file;
           ^~~~
/home/user/zonation/zonation-core-master/zig4lib/manager.h: In instantiation of ‘FileRef<Format>::operator bool() const [with Format = ZRasterFormat]’:
/home/user/zonation/zonation-core-master/zig4lib/proj_io_util.h:25:9:   required from ‘bool LoadOptionalFile::operator()(FileRef<Format>&, const FilePath&) [with Format = ZRasterFormat]’
/home/user/zonation/zonation-core-master/zig4lib/proj.cpp:64:97:   required from here
/home/user/zonation/zonation-core-master/zig4lib/manager.h:173:11: error: cannot convert ‘const boost::intrusive_ptr<FileImpl<ZRasterFormat> >’ to ‘bool’ in return
make[2]: *** [zig4lib/CMakeFiles/zig4lib.dir/proj.cpp.o] Error 1
make[1]: *** [zig4lib/CMakeFiles/zig4lib.dir/all] Error 2
make: *** [all] Error 2```

**Comment by Martin-Jung** [comment]
Hello, 
Sorry to hijack this thread but I am running into the same issues with most modern Linux distributions / boost libraries.
In another closed issue ( https://github.com/cbig/zonation-core/issues/15#issuecomment-287812051 )  it is mentioned that zonation can be compiled against the newest boost version, however (**a**) I did not manage to figure out how to do this yet and (**b**) fear that this might break my current distribution as a lot of software is dependent on boost.

@PKullberg Would you mind describing the steps you took to get it to run on Ubuntu 16.06 ?

Also: Would there maybe be an option to configure a docker image with a ready-to-run zonation configured? 

Cheers,
Martin

**Comment by jlehtoma** [comment]
> Would there maybe be an option to configure a docker image with a ready-to-run zonation configured?

This option has popped a couple of times overt the years and personally I think it would make a lot of sense. Here too the problem is that since Zonation is not actively maintained there's nobody to take up the task. I'd be happy to contribute what I can, but my knowledge on building Docker images is very limited. I opened [another issue](https://github.com/cbig/zonation-core/issues/21) to discuss options related to this approach.

**Comment by FedeMPouzols** [comment]
Hi (heippa @jlehtoma ja @hkujala! ;)),

A docker image is great to have, but we don't need to give up on compiling from sources. I took a look at the compilation issues and I think there are no major concerns. The beast is still alive and kicking. There was just a bit of boost obfuscation. The code is lagging behind as for C++11 features, which back in the day were not available in all compilers, but it is definitely not obsolete.

This branch:  https://github.com/FedeMPouzols/zonation-core/tree/issue19_compilation_issues_201903 compiles cleanly on my unstable debian. I'd expect it to be largely compatible with recent Ubuntu releases, and probably other flavors. If anyone can give it a try on a different system that would be great. Here are my dependency versions:
cmake: 3.13.4
libgdal-dev: 2.4.0+dfsg-1
fftw3-dev: 3.3.8
libqt4-dev: 4.8.7+dfsg-17
libqwt-dev: 6.1.4  (this one is not used in zig4 "core" I think)
boost: 1.67.0.1

I played a bit with the basic and advanced tutorial setups from https://github.com/cbig/zonation-tutorial and they all seem to run without issues.

**Comment by jlehtoma** [comment]
Moikka @FedeMPouzols , very happy to hear from you! Thanks a gazillion, I suspected that the beast still has plenty of steam in it, but fixing the things you did was just completely beyond my skills. I think it's definitely desirable to be able compile Zonation from source.

I'm happy to report that (after one minor modification, see below) I'm able to build your branch on openSUSE Tumbleweed with the following dependency versions:

```
cmake: 3.13.4-3.1
gdal-devel: 2.4.1-106.1
fftw3-devel: 3.3.8-1.1
libqt4-devel: 4.8.7-16.1
boost-devel: 1.69.0-1.1
``` 
I had to add `#include <iostream>` in the beginning of `zig4/core/bat_run.cpp` to get rid of compiler complaining something not being part of something (`gcc` version 8.3.1), but after that everything went very smoothly. Running the [Zonation tutorial](https://github.com/cbig/zonation-tutorial) also seems to work fine.

This is great and also should make creating a Docker image a breeze. Would you @FedeMPouzols mind creating a pull request on your fixes back to [cbig/zonation-core](https://github.com/cbig/zonation-tutorial)? I can do it as well, but credit where credit's due. And thanks again!

**Comment by jlehtoma** [comment]
I took the liberty to create the pull request and merge it to zonation-core `master`. Starting from 678505c05f6b2263c3af0254c3ce9eb51a9af538 things seem to compile. Closing this issue.
